using System;
using System.Collections.Generic;
using System.Text;

namespace CaveGame.Common.Game.Tiles
{
    public enum TileID : short
    {
        Void = 255,
        Air = 0,
        Stone, 
        Dirt, 
        Grass, 
        OakLog, 
        OakLeaves,
        Water, 
        StoneBrick, 
        ClayBrick, 
        Torch, 
        Clay,
        OakPlank, 
        EbonyPlank, 
        PinePlank, 
        RedwoodPlank,
        Granite,
        Sandstone, 
        Mud, 
        Sand,
        RedTorch,
        BlueTorch, 
        GreenTorch, 
        WhiteTorch,
        CopperOre, 
        IronOre, 
        GoldOre, 
        UraniumOre, 
        CobaltOre, 
        LeadOre,
        MudBrick, 
        SandBrick,
        IceBrick,
        CarvedStoneBrick,
        CarvedSandBrick, 
        MossyStoneBrick, 
        MossyStone,
        CubedStone,
        CubedSandstone,
        Cobweb, 
        Tallgrass, 
        Rope, 
        Vine, 
        Ladder, 
        Platform, 
        TNT, 
        Lava, 
        Sludge, 
        Obsidian,
        Snow, 
        Ice, 
        Mycelium, 
        CryingLily, 
        BlueOysterMushroom, 
        Poppy, 
        BlueTallgrass, 
        ArsenicOre, 
        GalliumOre,
        BlackEyedSusan, 
        Chrysanthemum, 
        ForgetMeNot, 
        Honeysuckle, 
        Hydrangea, 
        Lily,
        Magnolia,
        Orchid, 
        Plumeria, 
        Tulip, 
        HexenRoses,
        Glass, 
        OakSapling,
    }
}
